package com.cabbookingsystem.enums_role_permission;

public enum RoleEnum {

	ADMIN_DEFAULT_ACCESS, ADMIN_ALL_ACCESS, ADMIN_READ_ACCESS, ADMIN_WRITE_ACCESS, ADMIN_DELETE_ACCESS,

	USER_DEFAULT_ACCESS, USER_ALL_ACCESS, USER_READ_ACCESS, USER_WRITE_ACCESS, USER_DELETE_ACCESS
}
